version: '3.8'

services:
  angular-app:
    build:
      context: ./Frontend/ToDo.WebApp
    ports:
      - "4200:4200"

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "7128:7128"
      - "32768:32768"
    depends_on:
      - sql-server-db
    environment:
      - SQL_SERVER_CONNECTION_STRING=Server=localhost;Database=Unimax;Trusted_Connection=True;

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
    # command: >
    #     bash -c '
    #     /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Password123 -i docker-entrypoint-initdb.d/CreateAll.sql;
    #     echo "All done!";
    #     '

volumes:
  sql-server-data:
